apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/meshachdamilare/eduhub-apps-gitops.git
    targetRevision: main
    path: applicationset
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true